### ISSUE TITLE
v0.4.0 crashes when using dbus-send (unlike busctl, gdbus, qdbus)

### ISSUE THREAD

**Issue by jbeich** [MaxVerevkin/wl-gammarelay-rs#22]
Regressed by a95ad70dd264. See also https://github.com/swaywm/sway/issues/6577#issuecomment-1046316739

```
$ RUST_BACKTRACE=1 wl-gammarelay-rs &
New output: 52
Output 52: name = "DP-1"
Output 52: ramp_size = 1024

$ dbus-send --session --type=method_call --dest=rs.wl-gammarelay / rs.wl.gammarelay.ToggleInverted
todo: handle signal: Some("NameAcquired")
todo: handle signal: Some("NameAcquired")
thread 'main' panicked at rustbus-service-7401913/src/lib.rs:117:39:
not yet implemented
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rustbus_service::Service<D>::run
             at rustbus-service-7401913/src/lib.rs:117:39
   4: wl_gammarelay_rs::dbus_server::DbusServer::poll
             at wl-gammarelay-rs-0.4.0/src/dbus_server.rs:327:9
   5: wl_gammarelay_rs::main
             at wl-gammarelay-rs-0.4.0/src/main.rs:48:25
   6: core::ops::function::FnOnce::call_once
             at rustc-1.76.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MaxVerevkin** [comment]
I could not reproduce this, but the error should now be logged, instead of crashing everything.

**Comment by jbeich** [comment]
I confirm, now prints warnings instead:
```
$ wl-gammarelay-rs
[...]
dbus error: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.18 was not provided by any .service files
dbus error: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.19 was not provided by any .service files
[...]
dbus error: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.40 was not provided by any .service files

$ basuctl --user
NAME                                 PID PROCESS         USER             CONNECTION    UNIT                      SESSION    DESCRIPTION
:1.10                                  - -               -                -             -                         -          -
:1.11                                  - -               -                -             -                         -          -
:1.12                                  - -               -                -             -                         -          -
:1.13                                  - -               -                -             -                         -          -
:1.14                                  - -               -                -             -                         -          -
:1.15                                  - -               -                -             -                         -          -
:1.16                                  - -               -                -             -                         -          -
:1.17                                  - -               -                -             -                         -          -
:1.41                              97791 n/a             foo             :1.41         -                         -          -
:1.5                                   - -               -                -             -                         -          -
ca.desrt.dconf                         - -               -                -             -                         -          -
org.a11y.Bus                           - -               -                -             -                         -          -
org.freedesktop.DBus                   - -               foo             -             -                         -          -
org.freedesktop.Notifications          - -               -                (activatable) -                         -
rs.wl-gammarelay                       - -               -                -             -                         -          -
```

**Comment by MaxVerevkin** [comment]
Does it still happen?

**Comment by jbeich** [comment]
Yes:
```
$ wl-gammarelay-rs
New output: 66
Output 66: name = "DP-1"
Output 66: ramp_size = 1024
todo: handle signal: Some("NameAcquired")
todo: handle signal: Some("NameAcquired")
dbus error: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.306 was not provided by any .service files
dbus error: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.307 was not provided by any .service files
^C
```

**Comment by MaxVerevkin** [comment]
Can you share what is happening in `dbus-monitor`?

**Comment by jbeich** [comment]
```vala
$ (sleep 1; wl-gammarelay-rs 2>/dev/null) &
$ (sleep 5; dbus-send --session --type=method_call --dest=rs.wl-gammarelay / rs.wl.gammarelay.ToggleInverted) &
$ (sleep 7; dbus-send --session --type=method_call --dest=rs.wl-gammarelay / rs.wl.gammarelay.ToggleInverted) &
$ dbus-monitor --session
signal time=1711038376.143155 sender=org.freedesktop.DBus -> destination=:1.327 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.327"
signal time=1711038376.143184 sender=org.freedesktop.DBus -> destination=:1.327 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.327"
method call time=1711038377.737233 sender=:1.328 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1711038377.737247 sender=org.freedesktop.DBus -> destination=:1.328 serial=1 reply_serial=1
   string ":1.328"
signal time=1711038377.737257 sender=org.freedesktop.DBus -> destination=(null destination) serial=5 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.328"
   string ""
   string ":1.328"
signal time=1711038377.737263 sender=org.freedesktop.DBus -> destination=:1.328 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.328"
method call time=1711038377.737364 sender=:1.328 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RequestName
   string "rs.wl-gammarelay"
   uint32 0
signal time=1711038377.737374 sender=org.freedesktop.DBus -> destination=(null destination) serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "rs.wl-gammarelay"
   string ""
   string ":1.328"
signal time=1711038377.737380 sender=org.freedesktop.DBus -> destination=:1.328 serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string "rs.wl-gammarelay"
method return time=1711038377.737383 sender=org.freedesktop.DBus -> destination=:1.328 serial=4 reply_serial=2
   uint32 1
method call time=1711038381.927038 sender=:1.329 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1711038381.927050 sender=org.freedesktop.DBus -> destination=:1.329 serial=1 reply_serial=1
   string ":1.329"
signal time=1711038381.927056 sender=org.freedesktop.DBus -> destination=(null destination) serial=7 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.329"
   string ""
   string ":1.329"
signal time=1711038381.927064 sender=org.freedesktop.DBus -> destination=:1.329 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.329"
method call time=1711038381.927188 sender=:1.329 -> destination=rs.wl-gammarelay serial=2 path=/; interface=rs.wl.gammarelay; member=ToggleInverted
signal time=1711038381.927298 sender=org.freedesktop.DBus -> destination=:1.329 serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.329"
signal time=1711038381.927304 sender=org.freedesktop.DBus -> destination=(null destination) serial=8 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.329"
   string ":1.329"
   string ""
signal time=1711038381.927374 sender=:1.328 -> destination=(null destination) serial=3 path=/; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "rs.wl.gammarelay"
   array [
      dict entry(
         string "Inverted"
         variant             boolean true
      )
   ]
   array [
   ]
signal time=1711038381.927393 sender=:1.328 -> destination=(null destination) serial=4 path=/outputs/DP_1; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "rs.wl.gammarelay"
   array [
      dict entry(
         string "Inverted"
         variant             boolean true
      )
   ]
   array [
   ]
method return time=1711038381.927610 sender=:1.328 -> destination=:1.329 serial=5 reply_serial=2
error time=1711038381.927624 sender=org.freedesktop.DBus -> destination=:1.328 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=5
   string "The name :1.329 was not provided by any .service files"
method call time=1711038383.927026 sender=:1.330 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1711038383.927060 sender=org.freedesktop.DBus -> destination=:1.330 serial=1 reply_serial=1
   string ":1.330"
signal time=1711038383.927066 sender=org.freedesktop.DBus -> destination=(null destination) serial=9 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.330"
   string ""
   string ":1.330"
signal time=1711038383.927073 sender=org.freedesktop.DBus -> destination=:1.330 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.330"
method call time=1711038383.927148 sender=:1.330 -> destination=rs.wl-gammarelay serial=2 path=/; interface=rs.wl.gammarelay; member=ToggleInverted
signal time=1711038383.927235 sender=org.freedesktop.DBus -> destination=:1.330 serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.330"
signal time=1711038383.927247 sender=org.freedesktop.DBus -> destination=(null destination) serial=10 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.330"
   string ":1.330"
   string ""
signal time=1711038383.927342 sender=:1.328 -> destination=(null destination) serial=6 path=/; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "rs.wl.gammarelay"
   array [
      dict entry(
         string "Inverted"
         variant             boolean false
      )
   ]
   array [
   ]
signal time=1711038383.927360 sender=:1.328 -> destination=(null destination) serial=7 path=/outputs/DP_1; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "rs.wl.gammarelay"
   array [
      dict entry(
         string "Inverted"
         variant             boolean false
      )
   ]
   array [
   ]
method return time=1711038383.927498 sender=:1.328 -> destination=:1.330 serial=8 reply_serial=2
error time=1711038383.927503 sender=org.freedesktop.DBus -> destination=:1.328 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=8
   string "The name :1.330 was not provided by any .service files"
^C
```

**Comment by MaxVerevkin** [comment]
Okay, so `dbus-monitor` sends a method call, without `NO_REPLY_EXPECTED`, and exits immediately, without waiting for the reply. I suppose `ServiceUnknown` can be safely ignored, and not even logged?

**Comment by MaxVerevkin** [comment]
This error should be hidden now.
